import = ["/home/julien/.config/alacritty/catppuccin-frappe.toml"]

[font]
size = 12.0

[font.bold]
family = "MonaspiceKr Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MonaspiceXe Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MonaspiceRn Nerd Font"
style = "Italic"

[font.normal]
family = "MonaspiceNe Nerd Font"
style = "Regular"

[window]
opacity = 0.9
