import = ["/home/julien/.config/alacritty/catppuccin-frappe.toml"]

[font.bold]
family = "Monaspace Krypton"
style = "Bold"

[font.bold_italic]
family = "Monaspace Xenon"
style = "Bold Italic"

[font.italic]
family = "Monaspace Radon"
style = "Italic"

[font.normal]
family = "Monaspace Neon"
style = "Regular"

[window]
opacity = 0.9
